UX decign and start page layout.
Dubrovskiy-Konstantin/web_proj_js pull request #2
Opened 2022-03-11 15:31 UTC by Dubrovskiy-Konstantin

start working with project. 
UX in README.md

2022-03-17 18:39 UTC, Nastik1811 requested changes
There is a lack of html-tags in your wireframe.

2022-04-12 12:37 UTC, Dubrovskiy-Konstantin commented
Попробовал сделать что то нормальное (надеюсь). На самом деле выходит как-то тяжело и долго :(
Html и Css вроде ок, но js вообще убийственно 🤢. 
Можно еще пару вопросов:
    1. Зашел в тупик касательно бд. Думал сделать ее на джейсон-файлах на "сервере"(в папке внутри проекта), это же реализуемо? (а то погуглил, а там все про node.js) 
    2. Как можно реализовать всплывающее сообщение при hover на выделенной части текста элемента (для добавления аннотации). У меня текст песни выводится в textarea, и у меня не выходит подвязать :hover на ::selection (работает либо только одно, либо только другое)

2022-04-13 15:15 UTC, Nastik1811 commented
Так секунду. У вас же 2 лаба не была одобрена, куда html/css? И тем более js 👀

2022-04-13 15:22 UTC, Nastik1811 commented
И каждая лаба оформляется как отдельный PR

2022-04-13 15:22 UTC, nastik1811 commented
После того, как вы получили оценку за предыдущую

2022-04-17 13:26 UTC, Dubrovskiy-Konstantin commented
Хорошо, давайте со второй лабы :)
Мой UX-дизайн 😎

2022-04-17 13:28 UTC, Dubrovskiy-Konstantin commented
И скажите, нужно ли коллаборатора ре-реквестить? или и так уведомление приходит?
(гит не нов, но пул-реквесты не доводилось использовать)

2022-04-17 19:00 UTC, Nastik1811 commented
так, не переживайте, завтра посмотрю

2022-04-18 16:42 UTC, Nastik1811 commented
Не может быть больше 1 тега h1 на странице 
<img width="620" alt="image" src="https://user-images.githubusercontent.com/37243282/163841406-8d6e5cc6-fa58-4d56-a6d2-da6e6fb7fdf0.png">

2022-04-18 16:43 UTC, Nastik1811 approved these changes
С большего, вроде нормально, поставлю вам `8` за 2ю лабу.

2022-04-22 12:10 UTC, Dubrovskiy-Konstantin commented
Html Css и немного js-а чтоб работало хотя бы (переходы по страницам там, проверка на мобил/пк)
Всего на сайте 6 страниц: 5 линков с хедера и 1 если тыкнуть на итем в мэйне.
Сайт разместил на домене http://dixorab286666666.zzz.com.ua/#main
Правда, этот бесплатный домен умрет через 5 дней, но я его на tempmail регал так что все равно.

Проверял в хромовском f12 эмулятор мобильного вида. Работает, только нужно f5 прожать.
Пока при нынешнем функционале выглядит так. Позже может измениться немного (где-то может кнопка добавится, где-то еще что-то)

2022-04-25 12:36 UTC, Dubrovskiy-Konstantin commented
домену жить осталось 2 дня 😭
![image](https://user-images.githubusercontent.com/62993410/165090072-66dd0536-0d85-4992-a019-dd173599c7d4.png)
(っ °Д °;)っ
_(и я думал что при апруве оно замерждит само в ветку, но видимо нет. И все новые изменения приписались в этот же PR. Можно я исправлю уже со следующего? Или этот уже переделаю, но после того как вы проверите?)_

2022-04-27 14:54 UTC, Nastik1811 requested changes
Вам нужно отрефакторить ваши селекторы (т.е. преимущественно должны использоваться селекторы по классу), ну и ещё несколько замечаний ниже увидете. А так вроде неплохо

2022-04-27 14:54 UTC, Nastik1811 commented on css/login.css
> +}
здесь достаточно использовать в качестве селектора `#sign-in:checked`,  эта часть лишняя `#login-page input` . А лучше использовать в качестве селекторов классы.

2022-04-27 14:54 UTC, Nastik1811 commented on css/login.css
> +    width: 32ch;
Особенно здесь. Это неправильно стилизовать каждый элемент по отдельности (т.е. через id) когда у вас для набора элементов один и тот же стиль. 
Лучше сделать класс для этих трёх элементов (например, auth-input)  и использовать `.auth-input` вместо 
```
#login-page input#inputLogin,
#login-page input#inputPassword,
#login-page #submitButton 
```

2022-04-27 14:54 UTC, nastik1811 commented on css/login.css
> +    width: 32ch;
Кстати, зачем вы везде используете сложные селекторы вроде `#parent-id #child-id `? Это избыточная специфичность. id целевого элемента более чем достаточно, а во многих случаях, как я указала выше, стоит вообще использовать классы

2022-04-27 14:54 UTC, Nastik1811 commented on css/login.css
> +    transform: scale(1.1, 1.2);
Страшна.
Опять же, это могло быть просто `.auth-input:hover, .auth-input:focus`

2022-04-27 14:54 UTC, Nastik1811 commented on css/mobile.css
> +    max-height: 160px;
Если вы используете абсолютные значения в пикселях для width/height, max-width/max-height не имеют смысла

2022-04-27 14:54 UTC, Nastik1811 commented on css/mobile.css
> +    font-size: 42px !important;
зачем вам important здесь?

2022-04-27 14:54 UTC, Nastik1811 commented on css/profile.css
> +#profile-page form#upload-song textarea {
лучше бы вы сделали отдельный класс для нужной вам `textarea`. в будущем у вас может поменяться расположение элементов и стили слетят с такими селекторами

2022-04-27 14:54 UTC, Nastik1811 commented on index.html
> +                        <ol style="margin-left: 15px; min-width: 400px;">
Зачем вам inline-стили (их не разрешалось использовать)

2022-04-29 13:57 UTC, Dubrovskiy-Konstantin commented
Исправил недочеты: добавил некоторые классы, старался заменить те большие кучи селекторов на какой-то один, вынес в отдельные файлы inline-стили, ну и то все что вы там еще писали))).

По поводу 
> _Кстати, зачем вы везде используете сложные селекторы вроде #parent-id #child-id ? Это избыточная специфичность._


Для наглядности) Мне как то удобнее выносить все что на отдельной странице в отдельный css файл. Точно по этому же, я к каждому элементу обращаюсь как к ребенку родителя. (Раз я так делаю везде, то оно же ни на что не повлияет, типо там вес селектора или проч.). Вообще я бы хотел изначально какую то иерархию выделить, чтобы так просто в начале css файла разместить что то вроде:
```
#parent {
        #child1 {
                ...
        }
        #child2 {
                ...
        }
}
```
Но не нашел как, и приписывал #parent-a всем для этой самой иерархической наглядности. 
Такой типа "авторский стиль" ^_^

2022-04-30 11:27 UTC, Nastik1811 commented on css/main.css
> +    font-size: 100%;
Лучше не задавать шрифт в процентах, обычно используют `em`, `rem`, `px`

2022-04-30 11:29 UTC, Nastik1811 approved these changes
Интересно... Вообще это не очень правильно  🤔
Но ладно, в целом выглядит неплохо, за эту лабу `8`

2022-05-02 17:05 UTC, Nastik1811 commented
так, не забудьте замержить ветку

2022-05-02 17:20 UTC, merged